@startuml
'https://plantuml.com/class-diagram

class Tableau {
- nomTableau : String
- listeObjets : ArrayList<InterfaceListeTaches>
- archive : Archive
+ Tableau(pNom : String)
+ getNomTableau() : String
+ getArchive() : Archive
+ getListeObjets() : ArrayList<InterfaceListeTaches>
+ getListeTaches() : ArrayList<Tache>
+ getListeColonnes() : ArrayList<Colonne>
+ getTache(nomTache : String) : Tache
+ getColonne(nomColonne : String) : Colonne
+ getColonnes() : ArrayList<Colonnes>
+ ajouterColonne(col : Colonne) : void
+ supprimerColonne(col : Colonne) : void
+ ajouterTache(nomtache : String, nomColonne : String) : void
+ supprimerTache(nomTache : String, nomColonne : String) : void
+ archiverTache(nomTache : String, nomColonne : String) : void
+ desarchiverTache(nomTache : String) : void
+ archiverColonne(nomColonne : String) : void
+ desarchiverColonne(nomColonne : String) : void
+ enregistrerObservateur(o : Observateur) : void
+ supprimerObservateur(o : Observateur) : void
+ notifierObservateurs() : void
+ toString() : String
}

class Archive {
- listeTachesArchivees : ArrayList<Tache>
- listeColonnesArchivees : ArrayLsit<Tache>
+ Archive()
+ archiverTache(tache : Tache) : void
+ archiverColonne(colonne : Colonne) : void
+ desarchiverTache(tache : Tache) : void
+ desarchiverColonne(colonne : Colonne) : void
}

class ListeTableaux {
- tableaux : ArrayList<Tableau>
+ ListeTableaux()
+ ajouterTableau(tab : Tableau) : void
+ supprimerTableau(tab : Tableau) : void
+ getTableau(nomTab : String) : Tableau
+ getListeTableaux() : ArrayList<Tableau>
+ toString() : String
}

interface InterfaceListeTaches {
+ ajouterTache(tache : Tache) : void
+ supprimerTache(tache : Tache) : void
+ getTache(nomTache : String) : Tache
+ getListeTaches() : ArrayList<Tache>
}

class Colonne implements InterfaceListeTaches {
- nomColonne : String
- listeTaches : ArrayList<Tache>
+ Colonne(pNom : String)
+ getNomColonne() : String
+ ajouterTache(tache : Tache) : void
+ supprimerTache(tache : Tache) : void
+ getTache(nomTache : String) : Tache
+ getListeTaches() : ArrayList<Tache>
+ toString() : String
}

abstract class Tache {
# nomTache : String
# commentaire : String
# dateDebut : LocalDate
# dateFin : LocalDate
# listeDependances : ArrayList<Tache>
+ Tache(pNom : Tache)
+ getCommentaire() : String
+ getNomTache() : String
+ getDateDebut() : LocalDate
+ getDateFin() : LocalDate
+ getListeDependances() : ArrayList<Tache>
+ setCommentaire(com : String) : void
+ setDateDebut(dateD : LocalDate) : void
+ abstract setDateFin(dateF : LocalDate) : void
+ ajouterDependance(tache : Tache) : void
+ retirerDependance(tache : Tache) : void
+ equals(obj : Object) : boolean
+ abstract toString() : String
}

class TacheComplexe extends Tache implements InterfaceListeTaches {
- listeTaches : ArrayList<Tache>
+ TacheComplexe(pNom : String)
+ setDateFin(dateF : LocalDate) : void
+ ajouterTache(tache : Tache) : void
+ supprimerTache(tache : Tache) : void
+ getTache(nomTache : String) : Tache
+ getListeTaches() : ArrayList<Tache>
+ toString() : String
}

class TacheSimple extends Tache {
+ TacheSimple(pNom : String)
+ setDateFin(dateF : LocalDate) : void
+ toString() : String
}

class ControlArchivageColonne {
- tab : Tableau
+ ControlArchivageColonne(t : Tableau)
+ handle(event : ActionEvent) : void
}

class ControlArchivageTache {
- tab : Tableau
+ ControlArchivageTache(t : Tableau)
+ handle(event : ActionEvent) : void
+ extraireNomTacheDeID(idBouton : String) : String
}

class ControlBoutonModifTache {
- tab : Tableau
- listeNomTaches : ArrayList<String>
+ ControlBoutonModifTache(t : Tableau)
+ handle(event : ActionEvent) : void
+ majListeNomTaches() : void
+ extraireNomTacheDeID(idBouton : String) : String
}

class ControlCreationColonne {
- tab : Tableau
+ ControlCreationColonne(t : Tableau)
+ handle(event : ActionEvent) : void
}

class ControlCreationTableau {
- listeTab : ListeTableaux
+ ControlCreationTableau(lt : ListeTableaux)
+ handle(event : ActionEvent) : void
}

class ControlCreationTache {
- tab : Tableau
- listeNomColonnes : ArrayList<String>
+ ControlCreationTache(t : Tableau)
+ handle(event : ActionEvent) : void
+ majListeNomColonnes() : void
+ extraireNomColonneDeID(idBouton : String) : String
+ getListeNomColonnes() : ArrayList<String>
}

class ControlDesarchivageColonne {
- tab : Tableau
+ ControlDesarchivageColonne(t : Tableau)
+ handle(event : ActionEvent) : void
}

class ControlDesarchivageTache {
- tab : Tableau
+ ControlDesarchivageTache(t : Tableau)
+ handle(event : ActionEvent) : void
}

class ControlModificationTache {

}

class ControlSuppressionColonne {
- tab : Tableau
+ ControlSuppressionColonne(t : Tableau)
+ handle(event : ActionEvent) : void
+ extraireNomColonneDeID(idBouton : String) : String
}

class ControlSuppressionTableau {
- listeTab : ListeTableaux
+ ControlSuppressiontableau(t : Tableau)
+ handle(event : ActionEvent) : void
+ extraireNomtableauDeID(idBouton : String) : String
}

class ControlSuppressionTache {
- tab : Tableau
+ ControlSuppressionTache(t : Tableau)
+ handle(event : ActionEvent) : void
+ extraireNomColonneDeID(idBouton : String) : String
+ extraireNomTacheDeID(idBouton : String) : String
}


Tableau "1" --> "0...*" InterfaceListeTaches
Tableau "1" --> "1" Archive
Archive "1" --> "0...*" Colonne
Archive "1" --> "0...*" Tache
TacheComplexe "1" --> "0...*" Tache
ListeTableaux "1" --> "0...*" Tableau

@enduml